### ISSUE TITLE
大佬教一下

### ISSUE THREAD

**Issue by manhuaxian** [y377/189pan#2]

**Comment by y377** [comment]
不需要手动点击actions运行，根据设定的时间，时间一到立马运行，假设设定的比如此时（北京时间）2023-10-20 13:16，actions是不会运行的，actions是GMT时间，也就是会跟你设的时间慢8小时。

**Comment by manhuaxian** [comment]
哇哦，还得到回复了！！
那就再请问下大佬，我看到你的版本更新了，但是我fork的没有提示更新呢，正常是不是点一下code那里更新啊？
