### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by 3287134551** [y377/189pan#4]
一直提示验证码错误，您可以修复下吗

**Comment by y377** [comment]
> 一直提示验证码错误，您可以修复下吗

这并非脚本本身的问题，这是因为异地登陆引起的，临时的解决办法是：
**在本地通过浏览器访问云盘官网并且成功登录**

**Comment by 3287134551** [comment]
好的，谢谢，已经好了，谢谢您的开发
